### ISSUE TITLE
Possibility of using in the command line?

### ISSUE THREAD

**Issue by ChildishGiant** [ReFreezed/LuaSimpleSquish#1]
Hi there!

This seems to be just the tool I need but I'm wondering if it can be called directly from the commandline (`lua .\LuaSimpleSquish\simpleSquish.lua FILE_NAME --minify` or something like that). I've tried directly calling it but it seems that it doesn't work like this.

**Comment by ReFreezed** [comment]
It wasn't possible, but I've now added a command line utility (`simpleSquishCl.lua`).

Usage: `lua simpleSquishCl.lua <inputFile> <outputFile> <squishArguments>`
